spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chait8126po@gmail.com
    password: ${POEMAILPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: ws
  jpa:
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 5456
